server:
  port: 8077

logging:
#    level.org.mybatis: DEBUG
#    level.org.springframework.cloud.netflix: DEBUG
#    level.org.springframework: DEBUG
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#netflix.atlas.uri: http://localhost:7101/api/v1/publish/
turbine:
  aggregator:
    clusterConfig: OPEN-PAY-SERVICE
  appConfig: open-pay-service
  instanceUrlSuffix: /hystrix.stream
